sql

drop schema public cascade;
drop table user if exists;
create table user (
    id bigint generated by default as identity primary key,
    username varchar(50) not null,
    email varchar(100) not null unique,
    name varchar(50) not null,
    last_name varchar(50) not null
);

drop table follower if exists;
create table follower (
    id bigint generated by default as identity primary key,
    follower_id bigint not null,
    followed_id bigint not null
);

drop table post if exists;
create table post (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    content varchar(500) not null,
    created_at timestamp default current_timestamp
);

create table post_like (
    id bigint generated by default as identity primary key,
    post_id bigint not null,
    user_id bigint not null,
    created_at timestamp default current_timestamp,
    unique (post_id, user_id),
    foreign key (post_id) references post(id),
    foreign key (user_id) references user(id)
);
